AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'lib/templates/**/*.rb'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.3

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'lib/**/*.rake'
    - 'Guardfile'
    - 'Rakefile'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/dashboards/*'

Metrics/LineLength:
  Exclude:
    - 'app/dashboards/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Naming/FileName:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
